#!/usr/bin/perl

#This program prints all the distinct terms are in the sequence generated by a**b for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100.

use strict;
use warnings;
use List::MoreUtils;

my @arr = ();
my %seen = ();

&power(2,100);

sub power {
	my $lower = shift;
	my $upper = shift;
	my $pow;
	for(my $i = $lower; $i <= $upper; $i++) {
		for(my $j = $lower; $j<= $upper; $j++) { 
			$pow = $i**$j;			
	#		print "Power is $pow\n";
			if(!($seen{$pow})){
				push @arr, $pow;
				$seen{$pow} = 1;
			}
		}
	}
	my @arr = sort {$a <=> $b} @arr;
	print "arr is: @arr\n";
	print "length of arr is $#arr\n";
}
